name: clang-format check

on: push

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: '13'
